// Generated by gencpp from file pca9685_msgs/ServoState.msg
// DO NOT EDIT!


#ifndef PCA9685_MSGS_MESSAGE_SERVOSTATE_H
#define PCA9685_MSGS_MESSAGE_SERVOSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pca9685_msgs
{
template <class ContainerAllocator>
struct ServoState_
{
  typedef ServoState_<ContainerAllocator> Type;

  ServoState_()
    : port_num(0)
    , servo_type(0)
    , servo_rot(0.0)  {
    }
  ServoState_(const ContainerAllocator& _alloc)
    : port_num(0)
    , servo_type(0)
    , servo_rot(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _port_num_type;
  _port_num_type port_num;

   typedef int32_t _servo_type_type;
  _servo_type_type servo_type;

   typedef float _servo_rot_type;
  _servo_rot_type servo_rot;


    enum { STOP = 0 };
     enum { D009A = 1 };
     enum { D150A = 2 };
 

  typedef boost::shared_ptr< ::pca9685_msgs::ServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pca9685_msgs::ServoState_<ContainerAllocator> const> ConstPtr;

}; // struct ServoState_

typedef ::pca9685_msgs::ServoState_<std::allocator<void> > ServoState;

typedef boost::shared_ptr< ::pca9685_msgs::ServoState > ServoStatePtr;
typedef boost::shared_ptr< ::pca9685_msgs::ServoState const> ServoStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pca9685_msgs::ServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pca9685_msgs::ServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pca9685_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pca9685_msgs': ['/home/ubuntu/catkin_ws/src/pca9685_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pca9685_msgs::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pca9685_msgs::ServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pca9685_msgs::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pca9685_msgs::ServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pca9685_msgs::ServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pca9685_msgs::ServoState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pca9685_msgs::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "844ba134507d19332dd881679bd50ba2";
  }

  static const char* value(const ::pca9685_msgs::ServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x844ba134507d1933ULL;
  static const uint64_t static_value2 = 0x2dd881679bd50ba2ULL;
};

template<class ContainerAllocator>
struct DataType< ::pca9685_msgs::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pca9685_msgs/ServoState";
  }

  static const char* value(const ::pca9685_msgs::ServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pca9685_msgs::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 port_num\n\
int32 servo_type\n\
float32 servo_rot\n\
\n\
int32 STOP  = 0\n\
int32 D009A = 1\n\
int32 D150A = 2\n\
\n\
";
  }

  static const char* value(const ::pca9685_msgs::ServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pca9685_msgs::ServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port_num);
      stream.next(m.servo_type);
      stream.next(m.servo_rot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pca9685_msgs::ServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pca9685_msgs::ServoState_<ContainerAllocator>& v)
  {
    s << indent << "port_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port_num);
    s << indent << "servo_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo_type);
    s << indent << "servo_rot: ";
    Printer<float>::stream(s, indent + "  ", v.servo_rot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCA9685_MSGS_MESSAGE_SERVOSTATE_H
