(cl:defpackage i2cpwm_board-srv
  (:use )
  (:export
   "STOPSERVOS"
   "<STOPSERVOS-REQUEST>"
   "STOPSERVOS-REQUEST"
   "<STOPSERVOS-RESPONSE>"
   "STOPSERVOS-RESPONSE"
   "SERVOSCONFIG"
   "<SERVOSCONFIG-REQUEST>"
   "SERVOSCONFIG-REQUEST"
   "<SERVOSCONFIG-RESPONSE>"
   "SERVOSCONFIG-RESPONSE"
   "DRIVEMODE"
   "<DRIVEMODE-REQUEST>"
   "DRIVEMODE-REQUEST"
   "<DRIVEMODE-RESPONSE>"
   "DRIVEMODE-RESPONSE"
   "INTVALUE"
   "<INTVALUE-REQUEST>"
   "INTVALUE-REQUEST"
   "<INTVALUE-RESPONSE>"
   "INTVALUE-RESPONSE"
  ))

